version: '3.4'

services:
#database images
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
  discountdb:
    image: redis
  orderdb:
    image: mcr.microsoft.com/mssql/server
#api images
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/Microservice.Catalog/Dockerfile
  basket.api:
    image: basketapi
    build: 
      context: .
      dockerfile: src/Services/Microservice.Basket/Dockerfile
  discount.grpc:
    image: discountgrpc
    build: 
      context: .
      dockerfile: src/Services/Microservice.DiscountGrpc/Dockerfile
volumes:
  postgres_catalog:
  postgres_basket:
  postgres_discount:
