version: '3.4'

services:
#database images
  catalogdb:
    image: postgres
  basketdb:
    image: postgres
  distributedcache:
    image: redis
#api images
  catalog.api:
    image: catalogapi
    build:
      context: .
      dockerfile: src/Services/Microservice.Catalog/Dockerfile
  basket.api:
    image: basketapi
    build: 
      context: .
      dockerfile: src/Services/Microservice.Basket/Dockerfile
volumes:
  postgres_catalog:
  postgres_basket: